### ISSUE TITLE
Introduction - Examples of use-cases for Akka

### ISSUE THREAD

**Issue by jkugiya** [akka-ja/akka-doc-ja#13]
parent issue #7

**Comment by kencharos** [comment]
翻訳 100% 済
https://www.transifex.com/akka-ja/akka-doc-ja_2_4_11/translate/#ja/intro--use-cases/97898764

**Comment by jkugiya** [comment]
レビューしました。いくつか対案を「提案」のところにつけました。

**Comment by kencharos** [comment]
最近忙しくなり、対応おくれました。
レビューありがとうございます。リンク切れの箇所を修正して、提案いただいた内容で修正しました。

**Comment by jkugiya** [comment]
レビュー済みにしました。 @yugolf

**Comment by yugolf** [comment]
ありがとうございます。１つ目の日本語に若干違和感があったので提案を書いてみました。大した違いじゃないですが、いかがでしょうか？

**Comment by kencharos** [comment]
修正いただいた内容で問題ないです。ありがとうございます。

**Comment by yugolf** [comment]
確認ありがとうございます。
問題なく反映されたようなのでクローズしておきます。
http://akka-ja-2411-translated.netlify.com/intro/use-cases.html
